### ISSUE TITLE
What are the progress bar + symbols?

### ISSUE THREAD

**Issue by daveuk100** [vbauerster/getparty#10]
I have a question (not an issue). 

What does it mean when the progress bar shows + characters? I see this sometimes in retry/reconnect cases but I am not sure what the +'s represent?

```
P01:R00 609.6MiB 100% ============================================================== Avg: 2.6MiB/s Peak: 190.7MiB/s
P02:R00 609.6MiB 100% ============================================================== Avg: 1.4MiB/s Peak: 158.9MiB/s
P03:R01 609.6MiB 100% +++++++++++++++++++=========================================== Avg: 1.5MiB/s Peak: 158.9MiB/s
P04:R01 609.6MiB 100% ++++++++++++++++============================================== Avg: 1.5MiB/s Peak: 158.9MiB/s
```

**Comment by vbauerster** [comment]
As you correctly pointed out those appear after retry only which means download doesn't restart from scratch but continues from last retry. So `+`s indicate this much of bytes are preserved and the rest will be added on top. Hope my explanation makes sense.

**Comment by daveuk100** [comment]
Makes sense! Thank you.
