### ISSUE TITLE
Retry on initial failure to connect to the server

### ISSUE THREAD

**Issue by nwoodmsft** [vbauerster/getparty#11]
Hi! I noticed that in failure/disconnect scenarios, getparty is good at retrying connections that were already established, but I am wondering what your thoughts are on retrying of the initial (1st) connection?  For example, it seems that if the initial 1st connection to the server does not succeed, we give up immediately without a retry.

One test I did was to use a local firewall to block outbound port 80 and try to download from a http server, after one attempt the connection fails and is not retried. However, if the download is allowed to begin successfully and then a firewall is used to block outbound traffic half way through the download, I see getparty aggressively retries each of the parts and it is possible for it to reconnect later and succeed again (once traffic is no longer blocked by firewall).

Can we add retries for the initial connection too? I was looking at something like hashicorp's retryablehttp wrapper and it seemed to work quite well in other scenarios.

**Comment by nwoodmsft** [comment]
Offhand I was wondering if it's just a issue of cmd.follow() not retrying?

**Comment by vbauerster** [comment]
Hi!

> what your thoughts are on retrying of the initial (1st) connection?

It's not worth the trouble. I mean if initial connection fails it's an indicator of severe problem like network disconnected or resource is blocked. So problem needs user attention in first place. AFAIK wget behaves the same.

I tried retryablehttp in the past and it didn't work well, maybe things changed since then.

**Comment by nwoodmsft** [comment]
Thanks for sharing your thoughts on this! I appreciate the discussion.

Occasionally I have come across some content delivery networks with a large number of backend http servers and sometimes the initial server I am routed to will return an error (e.g. http 503 or 500 or another error indicating it is overloaded) and fail. On retry, I am routed through to a different backend server which succeeds. In those cases, a a retry has helped to get around the initial connection issue.

For that scenario, I tried switching over to retryablehttp instead of cleanhttp, and the results have been good so far. It looks like retryablehttp doesn't retry everything (so the truly pointless/fatal cases you mentioned like total lack of network or error 404 not found etc are not retried) but it will retry errors that are in 50* range like error 503 (with incremental backoff).

**Comment by vbauerster** [comment]
@nwoodmsft Can you pls try [follow-retry](https://github.com/vbauerster/getparty/tree/follow-retry) branch? It should retry follow (initial connection) if it returns server error 5xx status code. I didn't try myself.

**Comment by nwoodmsft** [comment]
Awesome thank you! Sorry I had missed this when you first create the branch/PR. Thanks for taking it!
