### ISSUE TITLE
Older Chrome/65 user-agent may be blocked

### ISSUE THREAD

**Issue by nwoodmsft** [vbauerster/getparty#13]
I encountered an issue where a download was being done via a proxy that can filter http requests (e.g. ZScaler) and one of the filters they have in place is designed to block older user-agents from performing http downloads. 

The intermediate server rejects the getparty connection with:

```
"AV_BROWSER_TYPE_BLOCK - Not allowed to use the browser Google Chrome 65"
````

I took a look at the code and I see that this is coming from our chrome user-agent string:

```
"chrome":  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
```

Is it possible to update this to a newer chrome user-agent string to avoid these types of blocks? The recommendation I received was that this should be at least Google Chrome 90 as 65 is old now.

Thanks!

**Comment by vbauerster** [comment]
Can you please make a PR for this?
Is it worth to introduce application's real user agent something like `getparty/version`? What do you think?

**Comment by nwoodmsft** [comment]
Yes will do - thank you.

Perhaps a custom version could be added as another option in our existing list of user-agents? Then the caller can select that version to use if any of the other versions are causing an issue (such as this problem with the filtering proxy). 

Should we also support the caller passing their own user-agent string for flexibility?

**Comment by vbauerster** [comment]
> Should we also support the caller passing their own user-agent string for flexibility?

`--user-agent` flag and header it represents could be overridden by `--header` flag like `-H 'User-Agent:value'`.  `-H` flag can be specified one or more times.

> Perhaps a custom version could be added as another option in our existing list of user-agents?

Feel free to add other well known user-agent string like `Edge` for example.

**Comment by nwoodmsft** [comment]
PR is raised, thanks! https://github.com/vbauerster/getparty/pull/14
