### ISSUE TITLE
[Feature Request] Custom user-agent

### ISSUE THREAD

**Issue by chromer030** [vbauerster/getparty#16]
Please add support for custom user agent, for example this input :
`./getparty -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36'`

In current default , the user-agents are hard-coded into this ones :
```
"chrome":   "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
"firefox":  "Mozilla/5.0 (Macintosh; Intel Mac OS X 11.4; rv:89.0) Gecko/20100101 Firefox/89.0",
"safari":   "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15",
"edge":     "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.37",
```

For some downloads , users need to set special user-agent in order to successfully download the file.
Thank you.

**Comment by vbauerster** [comment]
Pls see https://github.com/vbauerster/getparty/issues/13#issuecomment-845743818

**Comment by chromer030** [comment]
So it's possible to define user-agent with ```-H 'User-Agent:value'```.
Thank you.
I think the issue is closed.

**Comment by chromer030** [comment]
@vbauerster , Hi , I tried and it seems that `-H 'User-Agent:value'` for setting custom user-agent doesn't working.
This is output of test, please tell me if i'm doing something wrong :
```
./getparty -H 'User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36' --parts=8 --max-retry=25 'http://127.0.0.1:8080/neofetch-git'
```
Server incoming :
```
20:43:47 [INFO] 127.0.0.1:46620 "GET /neofetch-git HTTP/1.1" 206 46830 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" 0.000485
```

**Comment by vbauerster** [comment]
it's a bug. I've committed a fix.
