### ISSUE TITLE
-c is broken !

### ISSUE THREAD

**Issue by chromer030** [vbauerster/getparty#19]
Version : 1.16
OS : Linux amd64

```
user@user ~/Desktop % getparty -c 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
unexpected: run: open https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb: no such file or directory
```

**Comment by vbauerster** [comment]
`-c` expects path to json file saved from the last download session. You fed it with url and this error is expected (no such file or directory). You'll get same output with v1.15. If download session gets interrupted by whatever reason, getparty saves its state to a json file. To resume download you should either:

 - explicitly point to the json file via `-c` switch
 - provide same url without `-c` switch

**Comment by chromer030** [comment]
@vbauerster , the `-c=PATH of json file` is working and really thank you for tool and features, but is it possible to implement a feature to automatically detect json file of incomplete download without hard-defining json file with `-c` ?
Maybe `-c` for manually defining json file and `-C` for auto-detecting json and resume download ?
