### ISSUE TITLE
[Feature Support] One after another URLs downloading 

### ISSUE THREAD

**Issue by chromer030** [vbauerster/getparty#21]
Is this possible please to add feature of multi URL handling ?

Something like this : `getparty URL1 URL2 URL3 ...` and getparty download them automatically one after another.
This is useful when we have a multi part download and wanna simply use an internal feature instead of nq or pueue.
Thank you for everything.

**Comment by vbauerster** [comment]
I prefer to adhere [Do One Thing and Do It Well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well). I don't want to integrate queue management, because IMHO better tools do exists in that regard as you correctly named few.

**Comment by vbauerster** [comment]
You can get such behavior with:
```
$ echo URL1 URL2 URL3 ... | tr ' ' '\n' | xargs -P1 -n1 getparty
```

if you already have a file with urls then:
```
$ cat file_with_urls | xargs -P1 -n1 getparty
```
