### ISSUE TITLE
[BUG] HTTP response status codes

### ISSUE THREAD

**Issue by xiahuaijia** [vbauerster/getparty#23]
[getparty.go Line 673](https://github.com/vbauerster/getparty/blob/d7481dccc9c749a2289ff6fd9ee2b9ab11ad046d/getparty.go#L673)

```
func isServerError(status int) bool {
	return status > 499 && status < 500
}
```

[Server error responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses) (500 – 599)

**Comment by vbauerster** [comment]
Hi! Thanks for code review. Are you willing to submit a PR to fix this?
