### ISSUE TITLE
Unable to invoke getparty as a go pkg after removal of Run args

### ISSUE THREAD

**Issue by nwoodmsft** [vbauerster/getparty#28]
I think there was a recent refactor to remove the "args" parameter from the Run command:
https://github.com/vbauerster/getparty/commit/9391e71922cfc07bc795d55608252985bff2d150

Unfortunately, I think this breaks some use cases for the code, specifically projects which consume getparty as a golang pkg instead of via executable/binary.

For example, my usage of getparty is more similar to the following example where I have my own host binary which just directly calls into getparty.Run():

```
package main

import (
	"context"
	"os"
	"time"

	"github.com/vbauerster/getparty"
)

func main() {
	var opts []string
	opts = append(opts, "http://mydownload.com/myfile")
	opts = append(opts, "--parts=3")
	opts = append(opts, "--force")
	opts = append(opts, "--output=/home/user/downloads/myfile")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	cmd := &getparty.Cmd{
		Ctx: ctx,
		Out: os.Stdout,
	}

	err := cmd.Run(opts, "", "")
	if err != nil {
		panic(err)
	}
}
```

With the new changes to the Run command, this error below would be expected....but we don't seem to have a supported way to pass the 'opts' above to Run now (I don't think we can use os.Args as the args for our host binary are fixed and we cannot expose getparty arguments there):

```
# command-line-arguments
./main.go:26:27: too many arguments in call to cmd.Run
        have ([]string, string, string)
        want (string, string)
```

Is there a possiblity to revert the Run() changes or can we consider providing a new/supported way to invoke getparty/Run as a go pkg with ability to pass opts?

Thank you

**Comment by vbauerster** [comment]
Never thought somebody would use it like that. Sure I'll revert.

**Comment by nwoodmsft** [comment]
Thank you! 🙏
