### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chromer030** [vbauerster/getparty#4]
Thank You for this great project...it's really perfect and useful
if it's possible please add FTP & HTTPS , queuing feature and resume downloads after disconnection , option to hiding download parts to a temporary location and also overall current downloading speed and overall progress percentage...
I'm sure it will be greatest console download manager in future...
Thanks again...

**Comment by vbauerster** [comment]
Hello and you're welcome!
I don't plan to add FTP. Resuming is already there. Queuing can be achieved with help of shell script.

**Comment by chromer030** [comment]
an option for downloading links one by one from a txt file can be added please ?
like aria2c -i links.txt -j 1
this tool is very better and perfect than wget or aria2c.
thanks again man

**Comment by vbauerster** [comment]
You can use [nq](https://github.com/leahneukirchen/nq) utility to queue download jobs. For example:
```
nq -c getparty url1
nq -c getparty url2
fq
```

**Comment by vbauerster** [comment]
Yet another interesting task manager [pueue](https://github.com/Nukesor/pueue).

**Comment by chromer030** [comment]
Thank you very much , i think we can now close this issue.
