### ISSUE TITLE
Quiet option stills shows output when concatenating

### ISSUE THREAD

**Issue by daveuk100** [vbauerster/getparty#5]
I used the --quiet option with getparty and all output was silenced except for this:

Concatenating: 100% =================================== Done

Can we have the concatenating output also silenced with the --quiet option specified? 

Thanks

**Comment by vbauerster** [comment]
Thanks for reporting!
Should be fixed now. Can you please compile from latest master branch and check?
I've added [force](https://github.com/vbauerster/getparty/blob/e07ffd32289c08864726b612dfd026967f1883c1/getparty.go#L73) switch, which can be combined with `quiet` for complete silence.

**Comment by daveuk100** [comment]
I tried with master and the issue seems to be fixed - thank you! Will there be a new release shortly?

**Comment by daveuk100** [comment]
@vbauerster  I just saw one new issue - with --quiet specified there is something still outputting an empty line. I noticed that after I execute the cmd.Run with --silent there is a blank line on the console instead of no output.

**Comment by vbauerster** [comment]
Yes, there was [fmt.Fprintln(cmd.Out)](https://github.com/vbauerster/getparty/blob/a0aa2f26db64efb3aaef665b5de28e4488e25245/getparty.go#L316), which printed new line regardless of quiet switch. I have pushed patch to fix this.
Also keep in mind that if there is some error, it will be printed to stderr regardless of quiet switch.

**Comment by daveuk100** [comment]
Verified fixed - thank you!

**Comment by vbauerster** [comment]
> Will there be a new release shortly?

I'm about to release next version, but first would like you to confirm whether #6 has been fixed.

**Comment by daveuk100** [comment]
Thanks, I should be able to verify the fix later today
