### ISSUE TITLE
--no-check-cert option (InsecureSkipVerify) is not respected by cmd.follow()

### ISSUE THREAD

**Issue by nwoodmsft** [vbauerster/getparty#9]
### The --no-check-cert option (InsecureSkipVerify) is not respected by cmd.follow()

I noticed was that even if the --no-check-cert option was requested, the cmd.follow() function did not respect it and would still fail if the destination server certificate is untrusted.

Example of the issue:

```
$ ./getparty --no-check-cert https://insecure.server.com
2021/01/24 03:19:08 GET: https://insecure.server.com
unexpected exit: run: follow: Get "https://insecure.server.com": x509: certificate signed by unknown authority
```

I have raised a [pull request](https://github.com/vbauerster/getparty/pull/8) with a fix for this issue and I would also like to contribute a new related feature - support for specifying a custom set of root certificates for http client to trust when verifying the server certificate.

Thanks!

**Comment by vbauerster** [comment]
Thanks for contribution!
